In [1]:
import pandas as pd
import numpy as np

# Create dataset
data = {
    "Name": ["Rahul", "Amit", "Neha", "Riya", "Karan",
             "Rahul", "Simran", "Priya", "Arjun", "Vikas"],

    "Branch": ["CSE", "ECE", "CSE", "ECE", "MECH",
               "CSE", "MECH", "ECE", "CSE", "MECH"],

    "Marks": [85, 78, np.nan, 70, 88,
              85, 90, np.nan, 95, 60],

    "Age": [22, 25, 21, 23, np.nan,
            22, 24, 25, 22, np.nan]
}

df = pd.DataFrame(data)

# Save to CSV
df.to_csv("students_lab.csv", index=False)

print(df)

     Name Branch  Marks   Age
0   Rahul    CSE   85.0  22.0
1    Amit    ECE   78.0  25.0
2    Neha    CSE    NaN  21.0
3    Riya    ECE   70.0  23.0
4   Karan   MECH   88.0   NaN
5   Rahul    CSE   85.0  22.0
6  Simran   MECH   90.0  24.0
7   Priya    ECE    NaN  25.0
8   Arjun    CSE   95.0  22.0
9   Vikas   MECH   60.0   NaN

In [5]:
df = pd.read_csv("students_lab.csv")
print(df)

     Name Branch  Marks   Age
0   Rahul    CSE   85.0  22.0
1    Amit    ECE   78.0  25.0
2    Neha    CSE    NaN  21.0
3    Riya    ECE   70.0  23.0
4   Karan   MECH   88.0   NaN
5   Rahul    CSE   85.0  22.0
6  Simran   MECH   90.0  24.0
7   Priya    ECE    NaN  25.0
8   Arjun    CSE   95.0  22.0
9   Vikas   MECH   60.0   NaN

In [6]:
df.head()

    Name Branch  Marks   Age
0  Rahul    CSE   85.0  22.0
1   Amit    ECE   78.0  25.0
2   Neha    CSE    NaN  21.0
3   Riya    ECE   70.0  23.0
4  Karan   MECH   88.0   NaN

In [7]:
df.head(5)

    Name Branch  Marks   Age
0  Rahul    CSE   85.0  22.0
1   Amit    ECE   78.0  25.0
2   Neha    CSE    NaN  21.0
3   Riya    ECE   70.0  23.0
4  Karan   MECH   88.0   NaN

In [8]:
df.head(6)

    Name Branch  Marks   Age
0  Rahul    CSE   85.0  22.0
1   Amit    ECE   78.0  25.0
2   Neha    CSE    NaN  21.0
3   Riya    ECE   70.0  23.0
4  Karan   MECH   88.0   NaN
5  Rahul    CSE   85.0  22.0

In [9]:
df["Name"]

0     Rahul
1      Amit
2      Neha
3      Riya
4     Karan
5     Rahul
6    Simran
7     Priya
8     Arjun
9     Vikas
Name: Name, dtype: str

In [15]:
df1=df[df["Age"] > 23]

In [17]:
df1

     Name Branch  Marks   Age
1    Amit    ECE   78.0  25.0
6  Simran   MECH   90.0  24.0
7   Priya    ECE    NaN  25.0

In [18]:
df

     Name Branch  Marks   Age
0   Rahul    CSE   85.0  22.0
1    Amit    ECE   78.0  25.0
2    Neha    CSE    NaN  21.0
3    Riya    ECE   70.0  23.0
4   Karan   MECH   88.0   NaN
5   Rahul    CSE   85.0  22.0
6  Simran   MECH   90.0  24.0
7   Priya    ECE    NaN  25.0
8   Arjun    CSE   95.0  22.0
9   Vikas   MECH   60.0   NaN

In [20]:
df = df.drop_duplicates()

In [21]:
df

     Name Branch  Marks   Age
0   Rahul    CSE   85.0  22.0
1    Amit    ECE   78.0  25.0
2    Neha    CSE    NaN  21.0
3    Riya    ECE   70.0  23.0
4   Karan   MECH   88.0   NaN
6  Simran   MECH   90.0  24.0
7   Priya    ECE    NaN  25.0
8   Arjun    CSE   95.0  22.0
9   Vikas   MECH   60.0   NaN

In [22]:
df.isnull().sum()

Name      0
Branch    0
Marks     2
Age       2
dtype: int64

In [26]:
df["Marks"] = df["Marks"].fillna(df["Marks"].mean())
df["Age"] = df["Age"].fillna(df["Age"].mean())
df

     Name Branch      Marks        Age
0   Rahul    CSE  85.000000  22.000000
1    Amit    ECE  78.000000  25.000000
2    Neha    CSE  80.857143  21.000000
3    Riya    ECE  70.000000  23.000000
4   Karan   MECH  88.000000  23.142857
6  Simran   MECH  90.000000  24.000000
7   Priya    ECE  80.857143  25.000000
8   Arjun    CSE  95.000000  22.000000
9   Vikas   MECH  60.000000  23.142857

In [27]:
df.groupby("Branch")["Marks"].mean()

Branch
CSE     86.952381
ECE     76.285714
MECH    79.333333
Name: Marks, dtype: float64

In [28]:
df.groupby("Branch")["Marks"].agg(["mean", "max", "min", "count"])

             mean        max        min  count
Branch
CSE     86.952381  95.000000  80.857143      3
ECE     76.285714  80.857143  70.000000      3
MECH    79.333333  90.000000  60.000000      3

In [29]:
import pandas as pd
raw_data = [
    ['Alice', 'Engineering', 'Senior', 110000, 15000],
    ['Bob', 'Marketing', 'Junior', 70000, 5000],
    ['Charlie', 'Engineering', 'Senior', 100000, 12000],
    ['David', 'Marketing', 'Senior', 95000, 8000],
    ['Eva', 'Engineering', 'Junior', 85000, 6000],
    ['Frank', 'Marketing', 'Junior', 65000, 4000]
]
df2 = pd.DataFrame(raw_data)

In [30]:
df2

         0            1       2       3      4
0    Alice  Engineering  Senior  110000  15000
1      Bob    Marketing  Junior   70000   5000
2  Charlie  Engineering  Senior  100000  12000
3    David    Marketing  Senior   95000   8000
4      Eva  Engineering  Junior   85000   6000
5    Frank    Marketing  Junior   65000   4000

In [33]:
columns = ["Employee", "Team", "Level", "Salary", "Bonus"]
df2 = pd.DataFrame(raw_data, columns=columns)
df2

  Employee         Team   Level  Salary  Bonus
0    Alice  Engineering  Senior  110000  15000
1      Bob    Marketing  Junior   70000   5000
2  Charlie  Engineering  Senior  100000  12000
3    David    Marketing  Senior   95000   8000
4      Eva  Engineering  Junior   85000   6000
5    Frank    Marketing  Junior   65000   4000

In [35]:
df2['Team_Avg_Salary'] = df2.groupby('Team')['Salary'].transform('mean')
df2

  Employee         Team   Level  Salary  Bonus  Team_Avg_Salary
0    Alice  Engineering  Senior  110000  15000     98333.333333
1      Bob    Marketing  Junior   70000   5000     76666.666667
2  Charlie  Engineering  Senior  100000  12000     98333.333333
3    David    Marketing  Senior   95000   8000     76666.666667
4      Eva  Engineering  Junior   85000   6000     98333.333333
5    Frank    Marketing  Junior   65000   4000     76666.666667

In [36]:
df2['Team_Avg_Salary'] = df2.groupby('Team')['Salary'].transform('mean')
print(df2)

  Employee         Team   Level  Salary  Bonus  Team_Avg_Salary
0    Alice  Engineering  Senior  110000  15000     98333.333333
1      Bob    Marketing  Junior   70000   5000     76666.666667
2  Charlie  Engineering  Senior  100000  12000     98333.333333
3    David    Marketing  Senior   95000   8000     76666.666667
4      Eva  Engineering  Junior   85000   6000     98333.333333
5    Frank    Marketing  Junior   65000   4000     76666.666667